kind: Service
apiVersion: v1
metadata:
  name: k8ssandra-database
spec:
  type: ExternalName
  externalName: rihab-env-dc1-service.k8ssandra-operator.svc.cluster.local
  ports:
    - port: 9042
