apiVersion: v1
kind: Service
metadata:
  name: k8ssandra-lb
spec:
  selector:
    cassandra.datastax.com/cluster: rihab-env
    cassandra.datastax.com/datacenter: dc1
  ports:
    - port: 9042
      targetPort: 9042
  type: LoadBalancer