apiVersion: apps/v1
kind: Deployment
metadata:
  name: consume
  namespace: kafka
  labels:
    app: consume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consume
  template:
    metadata:
      labels:
        app: consume
    spec:
      containers:
        - name: consume
          image: spark-stream
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_SERVICE
              value: "10.103.23.230:9092"
          command: ["/opt/app/run.sh"]
          args: ["com.rihab.Consume"]
